apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "wihomet-clock.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
  labels:
    {{- include "wihomet-clock.labels" . | nindent 4 }}
spec:
  rules:
  - host: "wihomet-clock.1ng.me"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ include "wihomet-clock.fullname" . }}
            port:
              number: 8080