name: Deploy Services
on:
  workflow_dispatch:
    inputs:
        aws_region:
            description: "AWS Region"
            required: true
            default: "us-east-1"
        deploy-infra:
            description: "Deploy infrastructure"
            type: boolean
            required: true
            default: false
        # build-image:
        #     description: "Build Docker image"
        #     type: boolean
        #     required: true
        #     default: false    
        # helm-install:
        #     description: "Install Helm chart"
        #     type: boolean
        #     required: true
        #     default: false    
jobs:
    deploy-infra:
        uses: ./.github/workflows/terraform.yml
        if: ${{ github.event.inputs['deploy-infra'] == 'true' }}
        with:
            aws_region:  ${{ inputs.aws_region }}
    # build-image:
    #     uses: ./.github/workflows/build_app.yml
    #     if: ${{ github.event.inputs['build-image'] == 'true' }}  
    #     secrets: inherit  
    # helm-install:
    #     uses: ./.github/workflows/helm_install.yml
    #     if: ${{ github.event.inputs['helm-install'] == 'true' }}    
    #     secrets: inherit
