name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      aws_region:
        required: true
        type: string

# Permission can be added at job level or workflow level    
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
jobs:
  BuildAndPushDockerImage:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::092988563851:role/GitHubAction-AssumeRoleWithAction
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region:  ${{ inputs.aws_region }}
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Get a short version of the commit SHA
      - uses: benjlevesque/short-sha@v2.2
        id: short-sha
        with:
          length: 6

      # Print the short SHA
      - run: echo $SHA
        env:
          SHA: ${{ steps.short-sha.outputs.sha }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
            context: ./app
            file: ./app/Dockerfile
            platforms: linux/amd64,linux/arm64
            push: true
            tags: 092988563851.dkr.ecr.us-east-1.amazonaws.com/wihomet-ecr-repo:${{ steps.short-sha.outputs.sha }}