name: Dashboard

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      aws_region:
        description: "AWS Region"
        required: true
        default: "us-east-1"
      ecr_registry:  
        description: "ECR Registry"
        required: true
        default: "092988563851.dkr.ecr.us-east-1.amazonaws.com"
      build-image:
        description: "Build Update Heml"
        type: boolean
        required: true
        default: false
      deploy-infra:
        description: "Update Infra"
        type: boolean
        required: true
        default: false  
    #   helm-install:
    #     description: "Install Helm chart"
    #     type: boolean
    #     required: true
    #     default: false
jobs:
  build-image:
    uses: ./.github/workflows/build_app.yaml
    if: ${{ github.event.inputs['build-image'] == 'true' }}
    with:
      aws_region: ${{ inputs.aws_region }}
      ecr_registry: "${{ inputs.ecr_registry }}"

  deploy-infra:
    uses: ./.github/workflows/terraform.yaml
    if: ${{ github.event.inputs['deploy-infra'] == 'true' }}
    with:
      aws_region: ${{ inputs.aws_region }}   
