name: Terraform Plan

on:
    workflow_dispatch:

jobs:
    terraform:
        name: 'Terraform Plan'
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
            uses: actions/checkout@v2

        - name: Setup Terraform
            uses: hashicorp/setup-terraform@v1

        - name: Terraform Init
            run: terraform init infra

        - name: Terraform Plan
            run: terraform plan infra