on:
  workflow_call:
    inputs:
      aws_region:
        required: true
        type: string

# Permission can be added at job level or workflow level    
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
jobs:
  ApplyTerraformPlan:
    runs-on: ubuntu-latest
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::092988563851:role/GitHubAction-AssumeRoleWithAction
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region:  ${{ inputs.aws_region }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform -chdir=infra init
      - name: Terraform Plan
        run: terraform -chdir=infra plan
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: ichcc
          minimum-approvals: 1
          issue-title: "Infra Update"
          issue-body: "Review the terraform plan, then approve or deny"
          exclude-workflow-initiator-as-approver: false
      - name: Terraform Apply
        run: terraform -chdir=infra apply -auto-approve
